- README.md
- pyproject.toml
extending the readme with basic usage information and adding additional details to pyproject.toml
> modify readme and pyproject.toml for 1.0.0 release

- README.md
- pyroll/core/profile/hookimpls.py
- pyroll/core/profile/profile.py
- include hooks for surface and core temperature
- add a section about the hook policy into the readme
Please check my ideas about the policy!
> Surface Temperature and Hook Policy

- poetry.lock
- pyproject.toml
No errors occurred after update.
> Update Shapely to 2.0

- pyroll/core/hooks.py
- tests/hooks/test_extension_class.py
- tests/hooks/test_hook_functions.py
Problem: hooks added by plugins are not discovered by code completion
=> Added a pattern to declare a decorated derived class to enable code completion
See `tests/hooks/test_extension_class.py` for how to use it.
> Extension Hooks

- pyroll/core/__init__.py
- pyroll/core/disk_element/hookimpls.py
- pyroll/core/profile/profile.py
- pyroll/core/roll_pass/hookimpls/disk_element.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/sequence/hookimpls.py
- pyroll/core/unit/hookimpls.py
add some hooks originating from development of ring model and thermal-2d
> Disk Hooks

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/plugin_request.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix.md
- .github/PULL_REQUEST_TEMPLATE/new_feature.md
- CODE_OF_CONDUCT.md
- pyroll/core/roll_pass/hookimpls/deformation_unit.py
To enhance contribution from external developers templates for different types of pull requests as well as a Code of Conduct where added
> Include Templates for PRs as well as Code of Conduct

- pyroll/core/unit/unit.py
Add timing and respective logging to unit solve method for monitoring purposes.
> Add Timer to Unit Solve

- pyroll/core/roll_pass/hookimpls/roll.py
To give better approximation for this special case.
> add distinct contact length for square oval

- pyroll/core/roll_pass/hookimpls/deformation_unit.py
- pyroll/core/roll_pass/hookimpls/disk_element.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/roll_pass/roll_pass.py
- pyroll/core/transport/hookimpls.py
- pyroll/core/unit/hookimpls.py
- pyroll/core/unit/unit.py
- tests/test_solve.py
I have reviewed all existing hook implementations by the impression of #54 and refactored some things.
> Some Refactorings

- pyroll/core/roll_pass/hookimpls/roll_pass.py
Problem with Transport in first position has been fixed by using an additional try/except clause.
> Fix Issue #62

- pyroll/core/__init__.py
- pyroll/core/profile/hookimpls.py
- pyroll/core/profile/profile.py
- pyroll/core/roll/hookimpls.py
- pyroll/core/roll/roll.py
Add more hooks for thermal calculations
> Add more root hooks to roll

- pyroll/core/__init__.py
- pyroll/core/hooks.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/roll_pass/roll_pass.py
Added elongation efficiency property to the roll pass for further optimization task.
> Add elongation efficiency

- pyroll/core/profile/profile.py
- tests/profiles/test_fits_material.py
To define a standard way for material data hooks.
> Add `fits_material` Method to Profile

- pyroll/core/profile/hookimpls.py
- pyroll/core/unit/hookimpls.py
Since with old implementation Rotators made length to 0
> move default profile length = 0 to Unit.InProfile

- pyroll/core/unit/hookimpls.py
- tests/test_solve.py
To avoid requirement to give strain on every in profile.
> Add Default Strain=0 to Unit.InProfile

- pyroll/core/hooks.py
- tests/hooks/test_hook_functions.py
For retrieving the generic parameter on runtime.
> add type property to Hook

- pyroll/core/__init__.py
- pyroll/core/hooks.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/sequence/hookimpls.py
- pyroll/core/sequence/sequence.py
- pyroll/core/unit/hookimpls.py
- pyroll/core/unit/unit.py
Closes #85 
Energy consumption requires density!
> Power and Energy Hooks

- pyroll/core/profile/profile.py
- pyroll/core/roll/roll.py
> renamed thermal_capacity to specific_heat_capacity

- pyroll/core/grooves/generic_elongation.py
- tests/grooves/test_generic_for_errors.py
Added check as well as tests to solve Issue #94. 
Only remaining question would be to condense the check into separate functions with proper naming to increase readability.
> Added negative construction value check as well as tests

- pyroll/core/profile/hookimpls.py
- pyroll/core/roll_pass/hookimpls/helpers.py
- pyroll/core/roll_pass/hookimpls/profile.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/roll_pass/roll_pass.py
- pyroll/core/roll_pass/three_roll_pass.py
- change default to Y configuration
- change default in rp plot
Close #115
> Make Y Configuration the Default for 3RP

- pyroll/core/__init__.py
- pyroll/core/roll/roll.py
- pyroll/core/roll_pass/hookimpls/roll.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/roll_pass/roll_pass.py
Added more Hooks to roll and roll_pass.
Especially neutral_point, angle as well as entry angle to have this implemented never the less the plugin that one is using.
> Add Hooks for Angle Coordinates to Roll

- pyroll/core/roll_pass/hookimpls/roll.py
> updated neutral point calculation

- pyroll/core/profile/hookimpls.py
- pyroll/core/profile/profile.py
> added equivalent radius for profile

- pyroll/core/grooves/equivalent_ripped_groove.py
Changes to the equivalent ribbed groove. Please check for changes or merge into base repository
> added attributes for special values in the equivalent ribbed groove

- pyroll/core/profile/hookimpls.py
- pyroll/core/roll/hookimpls.py
> updated thermal_capacity to specific_heat_capacity

- pyproject.toml
- pyroll/core/grooves/spline.py
- tests/grooves/swedish_oval_test_groove.dxf
- tests/grooves/test_spline.py
> 109 dxf input for grooves and rolls

- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/roll_pass/roll_pass.py
> removed negative implementation of entry angle

- pyroll/core/sequence/sequence.py
> add filtered sequence lists

- pyroll/core/roll_pass/hookimpls/roll.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
- pyroll/core/roll_pass/roll_pass.py
Cherry pick exit stuff from #149.
> added forward slip and exit point as well as angle

- pyroll/core/sequence/sequence.py
- tests/test_pass_sequence.py
- tests/test_solve.py
May close #142.
@GRPlan is this what you meant?
> add label based indexing to pass sequence

- paper.md
I made some typographic edits to the JOSS paper.
> Update JOSS paper

- pyroll/core/config.py
- pyroll/core/profile/profile.py
- pyroll/core/roll_pass/deformation_unit.py
- pyroll/core/roll_pass/hookimpls/deformation_unit.py
- Added hook def and impl of Zener Holomon Parameter, as needed in a large bunch of model approaches.
- Added a couple of commonly used natural constants to config, to avoid future clashes between plugins defining all themselves in their config.
> Add Zener-Holomon Parameter

- pyroll/core/grooves/spline.py
- tests/grooves/test_spline.py
> updated test and file type from spline

- pyroll/core/profile/profile.py
> added hooks for microstructure calculation

- pyroll/core/sequence/sequence.py
> add drop, prepend and append methods to sequence

- pyroll/core/profile/profile.py
> Clarify definition of chemical composition

- pyroll/core/profile/hookimpls.py
- pyroll/core/profile/profile.py
> added astm grain size class

- pyroll/core/__init__.py
- pyroll/core/transport/cooling_pipe.py
- pyroll/core/transport/hookimpls/__init__.py
- pyroll/core/transport/hookimpls/cooling_pipe.py
- pyroll/core/transport/hookimpls/transport.py
- tests/cooling_pipe/test_cooling_pipe_values.py
> Added hooks and implementations to CoolingPipe

- pyroll/core/profile/profile.py
- pyroll/core/roll_pass/deformation_unit.py
- pyroll/core/roll_pass/hookimpls/deformation_unit.py
- pyroll/core/roll_pass/hookimpls/profile.py
- tests/profiles/test_profile_contours.py
> 193 add contour line and contour angles for profiles

- pyroll/core/profile/profile.py
- pyroll/core/roll_pass/hookimpls/deformation_unit.py
Closes #196.
Can be seen as a first solution until we come up with something like a contact zone, which we already discussed. 
For now this will do the trick.
> 196 add longitudinal and latitudinal contact friction

- pyroll/core/__init__.py
- pyroll/core/roll_pass/hookimpls/profile.py
> added `roll_pass.out_profile.velocity` to root hooks and provided basic implementation

- pyroll/core/roll_pass/hookimpls/profile.py
- pyroll/core/roll_pass/hookimpls/roll.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
> added missing - signs

- pyroll/core/roll/hookimpls.py
- pyroll/core/roll/roll.py
- pyroll/core/roll_pass/hookimpls/roll_pass.py
> changed nominal diameter to working diameter

- pyroll/core/rotator/hookimpls.py
Closes #232. 
Profile class not created, since it would be redundant to box.
> added default rotation for box in flat

- pyroll/core/roll_pass/hookimpls/roll_pass.py
> added default tensions

- pyroll/core/sequence/sequence.py
- tests/pass_sequence/test_pass_sequence_velocity_calculation.py
So I added the algorithm for calculation of the `roll_pass` velocities. One where the `initial_speed` has to be provided and one were the `final_speed` and `final_cross_section_area` has to be provided.
Closes #246.
> Added velocity calculation and test

- pyroll/core/roll_pass/roll_pass.py
> add contours_lines and classifiers to __attrs__ in RollPass

- pyroll/core/__init__.py
> added strain rate to root hooks for RollPass

- pyroll/core/__init__.py
I think a new micro is feasible up to here
> bump version to 2.1.9

- pyroll/core/rotator/hookimpls.py
> Add rotation of 0 for flat-flat roll passes

- pyroll/core/config.py
- tests/test_config.py
> allow parsing of enum config from env vars

- pyroll/core/roll_pass/hookimpls/roll.py
> fixed bug, setting wrong velocity

- pyroll/core/grooves/base.py
- pyroll/core/grooves/generic_elongation.py
- pyroll/core/grooves/spline.py
- pyroll/core/roll/hookimpls.py
- tests/roll_pass/test_roll_pass_profile_locations_disks.py
> added groove factor

- pyroll/core/sequence/sequence.py
- tests/pass_sequence/test_pass_sequence_forward_velocity_calculation.py
> 288 initial velocity in function solve velocities forward is interpreted incorrectly

- pyroll/core/roll/roll.py
> 297 add peclet number

- pyroll/core/sequence/sequence.py
- tests/pass_sequence/test_pass_sequence_flatten.py
> added flatten method and corresponding test

- pyroll/core/grooves/generic_elongation.py
- tests/roll/test_working_radius_from_lee_paper.py
Closes #301.
Added a test, but the differences between the models are quite sever so a comparison is kinda hard.
> 301 working radius not calcualted correct

- pyroll/core/__init__.py
- pyroll/core/unit/unit.py
> added convergence information

- pyroll/core/sequence/sequence.py
- tests/pass_sequence/test_pass_sequence_forward_velocity_calculation.py
> 312 setting wrong velocity in forward solution

- pyroll/core/__init__.py
- pyroll/core/roll_pass/hookimpls/base_roll_pass.py
- pyroll/core/sequence/sequence.py
- tests/pass_sequence/test_pass_sequence_interstand_tension_from_reduction.py
Closes #310. 
See #311  for a first impression of the idea.
> 310 calculate tension from given reduction velocity ratio

- pyroll/core/profile/profile.py
- tests/profiles/test_constructors.py
> 315 hexagon profile is wrongly scaled when corner radius is applied

- pyroll/core/__init__.py
- pyroll/core/roll_pass/hookimpls/profile.py
- tests/pass_sequence/test_pass_sequence_forward_velocity_calculation.py
- tests/test_solve_round_constricted_box_spreading.py
- tests/test_solve_round_flat_spreading.py
- tests/test_solve_round_oval_round_spreading.py
- tests/test_solve_square_oval_spreading.py
> Update cs with previous profile shape
