pyroll-project/pyroll-core

pyroll/core/roll_pass/base_plugins/width.py

Revert the width hook change since it converges at too high fillings.
Reverted to the old behaviour that $b_1 = b_0 \times \beta$

revert the width hook change from 302108523

---

pyroll/ui/cli/res/input_min.py

Fixed the values in input_min.py so that they are computable with real spreading models. Older version failed with Wusatowski by overfilling.

fix pass sequence of input_min.py

---

pyproject.toml
pyroll/core/roll_pass/base_plugins/strain.py

Fix bug in strain change.
If strain in a pass is low, sometimes negative strains occur in the first iteration, were ideal filling is assumed. Negative strains lead to failure of solution procedure. By assuming a negative strain to zero and issue a warning, iteration may continue and work properly.
In further iteration runs, the problem is often resolved, since the groove is underfilled and strain is positive again.

fix bug in strain change

---

pyroll/core/profile/hookspecs.py
pyroll/utils/hookutils.py
tests/utlis/test_for_materials.py

- Allow for usage of multiple material keys in `Profile.material` by using an iterable of strings as value. Old syntax with single string remains valid and is internally handled by `@for_materials` accordingly.
- Add `lower()` to profile and roll pass types decorators.
Need for possibility to define broader terms for materials like `profile.material = ["steel", "carbon_steel", "C45"]` to allow for material databases to give common data for material groups.

Multi materials

---

pyroll/core/shapes.py
tests/test_solve.py

Due to use of `__new__` constructor for geometries in shapely 2.0 old monkeypatches did not work anymore.
Old concept of replacement by derived classes does not work anymore, instead direct patching.

Fix shapely

---

pyroll/core/__init__.py
pyroll/core/config.py
pyroll/core/grooves/generic_elongation.py
pyroll/core/grooves/spline.py
pyroll/core/hooks.py
pyroll/core/profile/hookimpls.py
pyroll/core/roll/hookimpls.py
pyroll/core/roll/roll.py
pyroll/core/roll_pass/__init__.py
pyroll/core/roll_pass/hookimpls/profile.py
pyroll/core/roll_pass/hookimpls/roll.py
pyroll/core/roll_pass/hookimpls/roll_pass.py
pyroll/core/roll_pass/roll_pass.py
pyroll/core/roll_pass/three_roll_pass.py
pyroll/core/rotator/hookimpls.py
pyroll/core/unit/unit.py
tests/hooks/test_hook_functions.py
tests/test_solve3.py

- added a new `ThreeRollPass` class to represent roll passes with three working rolls
- implemented geometric core routines for their representation and instantiation
- removed `RollPass.upper_contour_line` and `RollPass.lower_contour_line` properties and replaced them with a sequential `RollPass.contour_lines`

Three-Roll Passes

---

pyroll/core/rotator/hookimpls.py

- Set default profile rotation to 90°.
- Leave only hook functions that differ from this behavior.
- So only special cases have to be regarded, since number of different shapes increased drastically with recent changes.

Simplify Rotations

---

pyroll/core/roll/hookimpls.py
pyroll/core/roll_pass/hookimpls/roll_pass.py

In some hooks on 'Roll' and 'RollPass' the value 2 Pi was missing.

Bug Fix: 2 Pi

---

pyroll/core/__init__.py
pyroll/core/config.py
pyroll/core/grooves/generic_elongation.py
pyroll/core/roll/hookimpls.py
pyroll/core/roll_pass/hookimpls/roll_pass.py
pyroll/core/unit/hookimpls.py
tests/test_config.py

During development of the CLI the need for parsing configuration values for the core and plugins from `config.toml` and perhaps envvars arose.
Module level constants could be altered depending on a heuristic to use all package level constants and such in `pyroll.<package>.config` modules.
But module level constants are error prone regarding imported references, for example one shall always import the config module and not the value itself (`from . import config` instead of `from .config import SOME_VAR`).
A static configuration class would be the better approach, since one could not accidentally import the var itself. To facilitate creation of such classes, the following helper classes and decorators are proposed.

Change Configuration

---

pyroll/core/hooks.py
pyroll/core/roll/roll.py
pyroll/core/roll_pass/roll_pass.py
pyroll/core/unit/unit.py
tests/hooks/test_hook_functions.py

During testing with multiple plugins (Lendl and Wusatowski) problems with caching of equivalent widths and/or widths occurred.
Needs:
- equivalent widths and/or widths must be preserved across iterations for spreading models
- shall not interfere with other plugins
Old approach: add them to `root_hooks`
Problems:
- root hook values on profiles are transferred to next unit
- conflicts with reverse equivalent calculation
New approach: retain cached values, but reevaluate the function cascade in order of dict contents (order of first evaluation)

Fix Iteration

---

pyroll/core/config.py
tests/test_config.py

During development of the CLI an error in the config processor appeared. The descriptors did not return themselves if no instance was given.
Also, the parser was not yielded to the new `ConfigValue` instance by the `config` decorator.

Fix ConfigValues

---

pyproject.toml
pyroll/core/grooves/generic_elongation.py
pyroll/core/grooves/generic_elongation_solvers.py

Solved #64 by replacing the bracketing interval $[0, \pi/2]$ in groove geometry solving by $[\epsilon, \pi/2-\epsilon]$ with $\epsilon=10^{-6}$. The value was tried out to effectively prevent the trigonometric function from getting 0 or 1, and so preventing division by zero in the numeric solvers.

Fix Issue #64

---

pyroll/core/roll_pass/hookimpls/roll_pass.py

Fix error encountered while using 3RP with FlatGroove and small reductions.
The flanks of the groove were considered as depth by `ThreeRollPass.height`, solved by clipping at `groove.usable_width`.

fix height of 3RP for small depths

---

pyroll/core/rotator/hookimpls.py

Due to non-intuitive behavior when using dedicated `Rotator`.

Add default duration = 0 to Rotator

---

pyroll/core/sequence/sequence.py

To make root hook values appear in PassSequence.out_profile as in the last subunit

overwrite PassSequence.OutProfile.root_hook_fallback with getting from last subunit

---

pyroll/core/hooks.py
tests/hooks/test_hook_functions.py

Implement hook wrapper functions (inspired by [pluggy](https://pluggy.readthedocs.io/en/stable/#wrappers)).
They take precedence over all other hook functions and allow to modify hook function results stemming from other places. They work as normal hook functions with `trylast` and `tryfirst`.
They must contain exactly one `yield` expression, the argument of `yield`, however, is ignored. It is just used to inject the lower level result value.
Use a `return` statement to return the modified result. See the tests for examples.
Pay attention on:
- The value of `(yield)` may be `None`, if no hook function at lower level returns a value. No exception is raised in this case by the framework, check yourself for `None` and react accordingly.
- The wrapper is called in cycle at `yield`, you have …

Hook Wrappers

---

pyroll/core/rotator/rotator.py
pyroll/core/unit/unit.py

Implementations acc. to the request in #67.
Two new methods in `Unit` which return the previous resp. next unit of a given type in the sequence.
Updated the existing methods in `Rotator` to make use of them.

impl Unit.prev_of and Unit.next_of methods

---

pyroll/core/transport/hookimpls.py

Due to question raised by K. van Putten.
Enables giving length in transports without specifying explicitly the velocity in conti processes.

Add fallback of transport velocity getting from prev unit velocity

---

pyroll/core/hooks.py
tests/hooks/test_hook_functions.py

To allow giving lambda functions as explicit hook value.
Only on explicit hook values callability will be checked. 
Allowed are parameterless functions and functions with one parameter (`self`).
So for example:
```python
Profile.round(
diameter=10e-3,
density=lambda self: 7.85 / (1 + 3 * 1e-5 * self.temperature),
)
```

Add Explicit Hook Functions

---

hatch.toml
pyproject.toml
pyroll/core/grooves/base.py
pyroll/core/profile/profile.py
pyroll/core/repr.py
pyroll/core/roll_pass/roll_pass.py
tests/grooves/test_plot.py
tests/profiles/test_plot.py
tests/roll_pass/test_plot.py

Closes #81 
- Mainly to enable plotting in IPython `_repr_html_` for fast visual checking while using notebooks.
- Does *not* create dependency on matplotlib, but add it as an extra `plot`.
- Methods only present if matplotlib available within current environement, otherwise raise `RuntimeError`.
- Not all types using the `ReprMixin` must implement the plot function. If not overidden, a `TypeError` is raised, which users of the `plot` method have to be aware of (`_repr_html_` just returns the property table alone in this case).

Add Plot Methods for Certain Objects

---

pyproject.toml
pyroll/core/__init__.py
pyroll/core/grooves/diamonds/diamond.py
pyroll/core/profile/profile.py
pyroll/core/unit/unit.py

Closes #80 
- Implement subclasses of `Profile` to get distinct properties returning the definition values (so that they are not copied to the unit profiles).
- Add respective properties to `DiamondGroove`, all other grooves introduce no new measures.

Remember init args

---

pyroll/core/roll_pass/hookimpls/roll_pass.py
pyroll/core/roll_pass/roll_pass.py
tests/roll_pass/test_roll_pass_plot.py

Add orientation for displaying vertical, diagonal and Y configurations of roll passes as requested in personal talk by @GRPlan.
Does not effect the meaning of height and width, just affects the display in `plot()`.
Meant to be implemented in `pyroll.report` the same way.
`orientation=0`
`orientation=90`
`orientation=45`
`orientation=-45`
`orientation=0`
`orientation=180`

Display orientation

---

pyroll/core/repr.py

Image now centered above property table.
Fixes issues with image scaling in deeply nested objects.

fix formatting of repr html with images

---

pyroll/core/roll_pass/hookimpls/roll_pass.py
pyroll/core/roll_pass/three_roll_pass.py
tests/roll_pass/test_three_roll_pass.py

Close #121 
Works for ovals, rounds and flats. If the curvature is narrower than a circle, this method fails.

add inscribed circle diameter hook and impls

---

pyroll/core/roll_pass/roll_pass.py
pyroll/core/transport/hookimpls.py
pyroll/core/unit/hookimpls.py
tests/transport/test_transport_length.py

Close #169 
- Transport `length` is calculated from `location` of adjacent roll passes (newly defined).
- Multiple transports between roll passes are allowed, but others must have a fixed length (or calculated by another hook).

Calc Transport Length from Pass Location

---

pyroll/core/config.py
pyroll/core/grooves/generic_elongation.py
pyroll/core/profile/profile.py
pyroll/core/roll_pass/hookimpls/helpers.py
tests/profiles/test_constructors.py

Close #170
- Helper function implemented to refine profile contours.
- Apply in profile constructors and `RollPass.OutProfile.CrossSection` impls.
With `Config.PROFILE_CONTOUR_REFINEMENT = 50`:

Impl Profile Contour Refinement

---

pyroll/core/unit/unit.py

Yields all profiles in the unit, including subunits.
Useful for plotting of results, fe on time axis.

Add Profiles Iterator to Unit

---

pyroll/core/repr.py

Subunits were displayed as string in rich html disply of Jupyter. Changed to display lists as one-column table. Make whole unit display a `<details>` for more compactness

fix display of units in repr html

---

pyroll/core/unit/unit.py
tests/unit/test_additional_inits.py

A list holding special init functions which are called just after the classic `init_solve` method while initializing the procedure in `solve`.
Add your functions to this list using `append`. Each subclass holds its own instance. Functions of base classes are evaluated first, then those of subclasses.
```python
def init_fun(self):
self.test_var = 42
Unit.additional_inits.append(init_fun)
```

Add Additional Init Functions to Init the Solution Procedure for Plugins

---

pyproject.toml
pyroll/core/__init__.py

Made some changes to resolve issue #195 on our end:
Changed `pyproject.toml` to install kaleido version 0.1.0.post1 when istalling `pyroll-core[plotly]` on Windows.
- this could also be changed to also check wether it is Windows 11, as its supposedly only an issue with that, but i cant confirm/ test, wheter or not this isnt also occuring on other windows versions.
Changed `__init__.py` to, when checking for available plotting backend, also raise an error on windows machines, if the wrong kaleido version is installed:
- if the wrong kaleido version is installed this will now raise `ValueError("Kaleido Version 0.1.0.post1 is required to use plotly on Windows machines")` when importing pyroll-core
- if plotly but no kaleido is installed the message `print("The kaleido package is required if …

195 windows 11 pyroll run gets stuck in an endless loop due to problems with kaleido package

---

hatch.toml
pyproject.toml
pyroll/core/__init__.py
pyroll/core/config.py
pyroll/core/grooves/base.py
pyroll/core/log.py
pyroll/core/profile/profile.py
pyroll/core/repr.py
pyroll/core/roll_pass/roll_pass.py
pyroll/core/shapes.py
tests/grooves/test_groove_plot.py
tests/profiles/test_profile_plot.py
tests/roll_pass/test_roll_pass_plot.py

To prevent errors by kaleido in default setup (see #195), plotly plots are not converted to static images anymore by default (so kaleido is not needed and therefore dependency can be removed). This also enables interactive elements in `.plot()` and `._repr_html_()`.
The plotting API is also refactored to force some figure defaults for both backends.
Users of `ReprMixin` now must only override `_plot_plotly_` and/or `_plot_matplotlib_` methods to enable plotting. They must return a figure object of the respective backend.

Remove Kaleido

---

pyroll/core/profile/profile.py
pyroll/core/roll_pass/hookimpls/deformation_unit.py
pyroll/core/roll_pass/hookimpls/roll.py
tests/profiles/test_profile_contours.py
tests/profiles/test_profile_contours_3fold.py
tests/roll/test_roll_contact_areas.py
tests/roll/test_roll_contact_areas_3fold.py
tests/test_solve.py
tests/test_solve_disks.py
tests/test_solve_spreading.py

Changed the Contact area calculation so that its more representative for three-roll rolling.
Also enhanced the contact_lines property to handle ThreeRollPasses correctly, as this is also required for coming changes in the Zouhar-Package.
Currently there is also a factor 0.999 necessary to correctly calculate the in_profile local_width - probably due to small numerical deviations.

238 contact area of three roll passes

---

pyroll/core/grooves/__init__.py
tests/grooves/test_create_groove.py

enables grooves construction like that
```python
import pyroll.core as pr
groove = pr.create_groove_by_type_name("swedish-oval groove", r1=1, r2=1, depth=3, usable_width=10, ground_width=6)
```

impl a helper function for construction grooves by name

---

pyroll/core/roll_pass/base.py
pyroll/core/roll_pass/deformation_unit.py
pyroll/core/roll_pass/hookimpls/base_roll_pass.py
pyroll/core/roll_pass/hookimpls/deformation_unit.py
pyroll/core/roll_pass/hookimpls/helpers.py
pyroll/core/roll_pass/hookimpls/roll.py
pyroll/core/roll_pass/hookimpls/three_roll_pass.py
pyroll/core/roll_pass/three_roll_pass.py
pyroll/core/roll_pass/two_roll_pass.py
tests/profiles/test_profile_contours.py
tests/profiles/test_profile_contours_3fold.py
tests/roll/test_roll_contact_areas_3fold.py
tests/roll_pass/test_roll_pass_technological_orientation.py
tests/roll_pass/test_three_roll_pass.py

to be in alignment with the technological hooks
report gives errors until https://github.com/pyroll-project/pyroll-report/commit/db85a49448c4d626aa9984fe556913936ea0fdfa is published

use multi line strings in all contour-line like properties and hooks

---

hatch.toml
pyproject.toml
pyroll/core/grooves/spline.py
tests/grooves/test_spline.py

- use `ezdxf-shapely` package for importing DXF data to `SplineGroove`
- make this package optional via an extra

Ezdxf shapely

---

pyroll/core/__init__.py
pyroll/core/config.py
pyroll/core/repr.py
tests/test_repr.py

close #278 
Configuration of preferred backend now possible via the `Config` class.
```python
from pyroll.core import Config, PlottingBackend
Config.PREFERRED_PLOTTING_BACKEND = PlottingBackend.MATPLOTLIB
Config.PREFERRED_PLOTTING_BACKEND = PlottingBackend.PLOTLY
```
If this throws an `ImportError` or a `NotImplementedError` the other backend is still used if available.

278 add possibility to configure plotting backend instead of standard preference

---

README.md

Please check and notice also the new rules for versioning.
Especially feature releases: we do not have to spare minor release versions. Making a new minor with each feature release enables easier dependency management in plugins and extensions.

Update Versioning in Readme
